#NAME: SARAN ADHIKARI
#UNIVERSITY ID: 2329794

#WORKSHEET0

#EXERCISE ON FUNCTIONS


Task-1

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.


• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.


• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [1]:
def convert_len(val,unit):
  if unit == "m":
    return val * 3.28084 #convert into ft
  elif unit == "ft":
    return val / 3.28084 #convert into m
  else:
    raise ValueError("Unsupported length unit.")

In [2]:
def convert_wt(val, unit):
  if unit == "kg":
    return val * 2.20462 #convert into lbs
  elif unit == "lbs":
    return val / 2.20462 #convert into kg
  else:
    raise ValueError("Unsupported weight unit.")

In [3]:
def convert_vol(val,unit):
  if unit == "L":
    return val * 3.78541 #convert into gal
  elif unit == "gal":
    return val / 3.78541 #convert into L
  else:
    raise ValueError("Unsupported volume unit.")

In [4]:
print("Choose Unit Converter!")
print("1. Length Converter")
print("2. Weight Converter")
print("3. Volume Converter")

try:
  option = int(input("Enter your choice (1/2/3): "))
  val = input("Enter the value to convert: ")
  val = float(val)

  if option == 1:
    unit = input("Enter the unit (m/ft): ")
    result = convert_len(val, unit)
    new_unit = "ft" if unit == "m" else "m"
    print(f"{val} {unit} is equal to {result} {new_unit}.")

  elif option == 2:
    unit = input("Enter the unit (kg/lbs): ")
    result = convert_wt(val, unit)
    new_unit = "lbs" if unit == "kg" else "kg"
    print(f"{val} {unit} is equal to {result} {new_unit}.")

  elif option == 3:
    unit = input("Enter the unit (L/gal): ")
    result = convert_vol(val, unit)
    new_unit = "gal" if unit == "L" else "L"
    print(f"{val} {unit} is equal to {result} {new_unit}.")
  else:
    print("Invalid choice.")

except ValueError as e:
  print(f"Error: {e}")
except Exception:
  print("An unexpected error occurred.")

Choose Unit Converter!
1. Length Converter
2. Weight Converter
3. Volume Converter
Enter your choice (1/2/3): 2
Enter the value to convert: 40
Enter the unit (kg/lbs): kg
40.0 kg is equal to 88.1848 lbs.


Task-2

Create a Python program that performs various mathematical operations on a list of numbers.


• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).


3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.


• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [5]:
def calculate_sum(nums):
  return sum(nums)

In [6]:
def average(nums):
  if not nums:
    raise ValueError("List is empty.")
  return sum(nums) / len(nums)

In [7]:
def maximum(nums):
  if not nums:
    raise ValueError("List is empty.")
  return max(nums)

In [8]:
def min(nums):
  if not nums:
    raise ValueError("List is empty.")
  return min(nums)

In [9]:
print("Mathematical Operations!")
print("Choose an operation")
print("1. Addition")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
  option = int(input("Enter your choice (1/2/3/4): "))
  nums = input("Enter a list of numbers separated by spaces: ")
  nums = [float(num) for num in nums.split()]

  if not nums:
    raise ValueError("List is empty.")

  elif option < 1 or option > 4:
    print("Invalid choice.")

  elif option == 1:
    result = calculate_sum(nums)
    print(f"The sum of the numbers is: {result}")

  elif option == 2:
    result = average(nums)
    print(f"The average of the numbers is: {result}")

  elif option == 3:
    result = maximum(nums)
    print(f"The maximum of the numbers is: {result}")

  elif option == 4:
    result = min(nums)
    print(f"The minimum of the numbers is: {result}")

  else:
    print("Invalid choice.")

except ValueError as e:
  print(f"Error: {e}")
except Exception:
  print("An unexpected error occurred.")


Mathematical Operations!
Choose an operation
1. Addition
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 1
Enter a list of numbers separated by spaces: 4 4 
The sum of the numbers is: 8.0


#EXERCISE ON LIST MANIPULATION

TASK-1

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:
Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [10]:
def extract_every_other(lst):
  return lst[::2]

In [11]:
example_list = [1,2,3,4,5,6]
result = extract_every_other(example_list)
print(result)

[1, 3, 5]


TASK-2

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].


In [12]:
def get_sublist(lst,start,end):
  return lst[start:end+1]

In [13]:
example_list = [1,2,3,4,5,6]
result = get_sublist(example_list,2,4)
print(result)

[3, 4, 5]


TASK-3

Write a Python function that reverses a list using slicing.

• Requirements:
Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [14]:
def reverse_list(lst):
  return lst[::-1]

In [15]:
example_list = [1,2,3,4,5,6]
result = reverse_list(example_list)
print(result)

[6, 5, 4, 3, 2, 1]


TASK-4

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [16]:
def remove_first_last(lst):
  return lst[1:-1] if len(lst) > 2 else []

In [17]:
example_list = [1,2,3,4,5,6]
result = remove_first_last(example_list)
print(result)

[2, 3, 4, 5]


TASK-5

Write a Python function that extracts the first n elements from a list.

• Requirements:

Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [18]:
def get_first_n(lst, n):
  return lst[:n]

In [19]:
example_list = [1,2,3,4,5,6]
result = get_first_n(example_list, 3)
print(result)

[1, 2, 3]


TASK-6

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [20]:
def get_last_n(lst, n):
  return  lst[n:] if n > 0 else []

In [21]:
example_list = [1,2,3,4,5,6]
result = get_last_n(example_list, 3)
print(result)

[4, 5, 6]


TASK-7

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [22]:
def reverse_skip(lst):
  return lst[-2::-2]

In [23]:
example_list = [1,2,3,4,5,6]
result = reverse_skip(example_list)
print(result)

[5, 3, 1]


#EXERCISE ON NESTED LIST

TASK-01

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [24]:
def flatten(lst):
  flat_list = []
  for sublist in lst:
    flat_list.extend(sublist)
  return flat_list

In [25]:
example_list = [[1,2],[3,4],[5,6]]
result = flatten(example_list)
print(result)

[1, 2, 3, 4, 5, 6]


TASK-2

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [26]:
def nested_element(lst, indices):
  element = lst
  for index in indices:
    element = element[index]
  return element

In [27]:
example_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1,2]
result = nested_element(example_list, indices)
print(result)

6


TASK-3

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [28]:
def nested_sum(lst):
  total = 0
  for item in lst:
    if isinstance(item, list):
      total += nested_sum(item)
    else:
      total += item
  return total

In [29]:
example_list = [[1, 2], [3, [4, 5]], 6]
result = nested_sum(example_list)
print(result)

21


TASK-4

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [30]:
def remove_element(lst, element):
  if isinstance(lst, list):
    return [remove_element(sublist, element) for sublist in lst if sublist != element]
  return lst

In [31]:
example_list = [[1,2],[3,2],[4,5]]
element_to_remove = 2
result = remove_element(example_list, element_to_remove)
print(result)

[[1], [3], [4, 5]]


TASK-5

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [32]:
def find_max(lst):
  max_val = float('-inf')
  for item in lst:
    if isinstance(item, list):
      max_val = max(max_val, find_max(item))
    else:
      max_val = max(max_val, item)
  return max_val

In [33]:
example_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(example_list)
print(result)

6


TASK-6

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [34]:
def count_occurrences(lst, element):
  count = 0
  for item in lst:
    if isinstance(item, list):
      count += count_occurrences(item, element)
    elif item == element:
      count += 1
  return count

In [35]:
example_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(example_list, element_to_count)
print(result)

3


TASK-7

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [36]:
def deep_flatten(lst):
  flat_list = []
  for item in lst:
    if isinstance(item, list):
      flat_list.extend(deep_flatten(item))
    else:
      flat_list.append(item)
  return flat_list

In [37]:
example_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(example_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


TASK-8

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [38]:
def nested_avg(lst):
  def flatten(lst):
    flat_list = []
    for item in lst:
      if isinstance(item, list):
        flat_list.extend(flatten(item))
      else:
        flat_list.append(item)
    return flat_list
  flat_list = flatten(lst)
  return sum(flat_list) / len(flat_list) if flat_list else 0

In [39]:
example_list = [[1, 2], [3, 4], [5, 6]]
result = nested_avg(example_list)
print(result)

3.5


#EXERCISE ON NUMPY

In [40]:
import numpy as np

BASIC VECTOR AND MATRIX OPERATION WITH NumPy

PROBLEM-01

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [41]:
#Task01
empty_array = np.empty((2,2))
print("Empty 2x2 Array: \n", empty_array)

Empty 2x2 Array: 
 [[2.17236084e-316 0.00000000e+000]
 [1.52715095e+160 5.49459198e+174]]


In [42]:
#Task02
ones_array = np.ones((2,2))
print("Ones 2x2 Array: \n", ones_array)

Ones 2x2 Array: 
 [[1. 1.]
 [1. 1.]]


In [43]:
#Task03
fill_value_array = np.full((3,3), 7)
print("Array filled with value 5: \n", fill_value_array)

Array filled with value 5: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [44]:
#Task04
reference_array = np.array([[1,2,3],[4,5,6]])
zeros_like_arrayr = np.zeros_like(reference_array)
print("Zeros like reference array: \n", zeros_like_arrayr)

Zeros like reference array: 
 [[0 0 0]
 [0 0 0]]


In [45]:
#Task05
ones_like_array = np.ones_like(reference_array)
print("Ones like reference array: \n", ones_like_array)

Ones like reference array: 
 [[1 1 1]
 [1 1 1]]


In [46]:
#Task06
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("Numpy array from list: ", numpy_array)

Numpy array from list:  [1 2 3 4]


PROBLEM-02

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [47]:
#Task01
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49: \n", array_10_49)

Array from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [48]:
#Task02
matrix_3x3 = np.arange(9).reshape(3,3)
print("3x3 Matrix: \n", matrix_3x3)

3x3 Matrix: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
#Task03
identity_matrix = np.eye(3)
print("3x3 Identity Matrix: \n", identity_matrix)

3x3 Identity Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#Task04
random_array = np.random.random(30)
print("Random Array \n", random_array)
mean_value = random_array.mean()
print("Mean value of random array: ", mean_value)

Random Array 
 [0.30566931 0.20241863 0.14089787 0.93125665 0.6471646  0.48019835
 0.36955888 0.18069507 0.46261295 0.74236537 0.86775263 0.40040378
 0.55817378 0.56326166 0.66764367 0.305395   0.3982378  0.88398947
 0.90616143 0.09784726 0.40599439 0.95644786 0.27852611 0.88632842
 0.34797923 0.69737509 0.50264873 0.07544609 0.88740479 0.24218403]
Mean value of random array:  0.5130679638556569


In [51]:
#Task05
random_matrix = np.random.random((10, 10))
print("Random 10x10 Matrix: \n", random_matrix)
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Minimum value: ", min_value)
print("Maximum value: ", max_value)

Random 10x10 Matrix: 
 [[0.15255664 0.80721042 0.93990898 0.83701879 0.57405618 0.43712455
  0.27952066 0.73376157 0.2845177  0.73984045]
 [0.35135843 0.54981035 0.85042965 0.37035725 0.71833143 0.23297026
  0.2232234  0.00143054 0.23603438 0.42181193]
 [0.760035   0.54952251 0.56382703 0.64136604 0.15024734 0.63851111
  0.82320485 0.5971601  0.494628   0.30698572]
 [0.28361495 0.83738753 0.84809194 0.22624572 0.10703263 0.48998626
  0.48242332 0.98009648 0.40578628 0.3873725 ]
 [0.60236287 0.8934767  0.61418572 0.64337938 0.00189981 0.72299339
  0.53509141 0.54433592 0.72546606 0.25141525]
 [0.7230869  0.9534571  0.41127841 0.07853749 0.0497173  0.93520507
  0.94165204 0.05509216 0.47737949 0.97713983]
 [0.33013906 0.46471684 0.54576332 0.48082811 0.52570937 0.12677577
  0.78739778 0.18919339 0.63959414 0.55275758]
 [0.22527782 0.86898235 0.09543554 0.30412082 0.34976244 0.82886814
  0.26579497 0.11210255 0.32657703 0.01567176]
 [0.21636408 0.33734707 0.32996188 0.95440505 0.58387777 

In [52]:
#Task06
zero_array = np.zeros(16)
zero_array[4] = 1
print("Array with value 1 at index 4: \n", zero_array)

Array with value 1 at index 4: 
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [53]:
#Task07
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("Reversed array: ", reversed_arr)

Reversed array:  [0 4 0 0 2 1]


In [54]:
#Task08
border_array = np.ones((5,5))
border_array[1:-1, 1:-1] = 0
print("Border array: \n", border_array)

Border array: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
#Task09
checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard pattern: \n", checkerboard)

Checkerboard pattern: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


PROBLEM-03

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [56]:
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [57]:
#Task01
addition_result = x + y
print("Addition Result: \n", addition_result)

Addition Result: 
 [[ 6  8]
 [10 13]]


In [58]:
#Task02
subtraction_result = x - y
print("Subtraction Result: \n", subtraction_result)

Subtraction Result: 
 [[-4 -4]
 [-4 -3]]


In [59]:
#Task03
multiplication_result = x * y
print("Multiplication Result: \n", multiplication_result)

Multiplication Result: 
 [[ 5 12]
 [21 40]]


In [60]:
#Task04
square_result = x ** 2
print("Square Result: \n", square_result)

Square Result: 
 [[ 1  4]
 [ 9 25]]


In [61]:
#Task05
dot_vw = np.dot(v,w)
print("Dot Product of v and w: ", dot_vw)
dot_xv = np.dot(x,v)
print("Dot Product of x and v: ", dot_xv)
dot_xy = np.dot(x,y)
print("Dot Product of x and y: \n", dot_xy)

Dot Product of v and w:  219
Dot Product of x and v:  [29 77]
Dot Product of x and y: 
 [[19 22]
 [50 58]]


In [62]:
#Task06
concat_xy_rows = np.concatenate((x,y), axis=0)
print("Concatenated x and y rows: \n", concat_xy_rows)

Concatenated x and y rows: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [63]:
concat_vw_cols = np.vstack((v, w))
print("Concatenated v and w columns: \n", concat_vw_cols)

Concatenated v and w columns: 
 [[ 9 10]
 [11 12]]


In [64]:
#Task07
try:
  concat_xv = np.concatenate((x,v), axis=0)
  print("Concatenation of x and v: ", concat_xv)
except ValueError as e:
  print("\nError in concatenation of x and v:", e)



Error in concatenation of x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Explanation of Error: Explanation: The shapes of x (2x2) and v (1x2) do not match along axis 0.
          To concatenate them, v should be reshaped into a (2x2) matrix

PROBLEM-04

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}


In [65]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

In [66]:
#1. Prove A.A^(-1) = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("Identity Matrix: \n", identity_matrix)

Identity Matrix: 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [67]:
#2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB: \n", AB)
print("BA: \n", BA)
is_equal = np.array_equal(AB, BA)
print("Are AB and BA equal?", is_equal)

AB: 
 [[23 13]
 [51 29]]
BA: 
 [[36 44]
 [13 16]]
Are AB and BA equal? False


In [68]:
#3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
B_T_A_T = np.dot(B_T, A_T)
print("AB^T: \n", AB_T)
print("B^T * A^T: \n", B_T_A_T)
is_equal = np.array_equal(AB_T, B_T_A_T)
print("Are AB^T and B^T * A^T equal?", is_equal)

AB^T: 
 [[23 51]
 [13 29]]
B^T * A^T: 
 [[23 51]
 [13 29]]
Are AB^T and B^T * A^T equal? True


In [69]:
# Given Equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Representing in matrix form AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using A^(-1) * B
A_inv_eq = np.linalg.inv(A_eq)
X_eq = np.dot(A_inv_eq, B_eq)

print("Solution to the system of equations: \n", X_eq)


Solution to the system of equations: 
 [ 2.  1. -2.]


In [70]:
# Using np.linalg.solve function
X_solution_using_function = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve: \n", X_solution_using_function)

Solution using np.linalg.solve: 
 [ 2.  1. -2.]


#HOW FAST IS NumPy


In [71]:
import time

ELEMENT WISE ADDITION

Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [72]:
size = 1_000_000

list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise addition using Python lists
start_time = time.time()
list_result = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

print(f"Time taken for element-wise addition using Python lists: {end_time - start_time} seconds")

Time taken for element-wise addition using Python lists: 0.18433260917663574 seconds


In [73]:
# Creating two NumPy arrays of size 1,000,000
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
array_result = array1 + array2
end_time = time.time()

print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time} seconds")

Time taken for element-wise addition using NumPy arrays: 0.009046077728271484 seconds


ELEMENT-WISE MULTIPLICATION

Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.

Measure and Print the time taken for this operation.

Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [74]:
list1 = list(range(1, size + 1))
list2 = list(range(1, size + 1))

# Measure time for element-wise multiplication using Python list
start_time = time.time()
list_result = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise multiplication using Python lists: ", end_time - start_time, "seconds")

Time taken for element-wise multiplication using Python lists:  0.19655656814575195 seconds


In [75]:
# Creating two NumPy arrays of size 1,000,000
array1 = np.arange(1, size + 1)
array2 = np.arange(1, size + 1)

#  Measure the time for element-wise multiplication using NumPy arrays
start_time = time.time()
array_result = array1 * array2
end_time = time.time()

print(f"Time taken using NumPy arrays: {end_time - start_time: .6f} seconds")

Time taken using NumPy arrays:  0.004343 seconds


DOT PRODUCT

Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [76]:
size = 1_000_000

list1 = list(range(1, size + 1))
list2 = list(range(1, size + 1))

# Measure time for dot product using Python list
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Time taken using Python lists: {end_time - start_time:.6f} seconds")

Time taken using Python lists: 0.094242 seconds


In [77]:
# Creating two NumPy arrays with values from 1 to 1,000,000
array1 = np.arange(1, size + 1)
array2 = np.arange(1, size + 1)

# Measure the time for dot product using NumPy arrays
start_time = time.time()
dot_product = np.dot(array1, array2)
end_time = time.time()

print(f"Time taken using NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken using NumPy arrays: 0.001368 seconds


MATRIX MULTIPLICATION

Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [78]:
import random

size = 1000
#  Generate two 1000x1000 matrices with random values between 1 and 10
matrix1 = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1, 10) for _ in range(size)] for _ in range(size)]

start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()

print(f"Time taken using Python lists: {end_time - start_time:.6f} seconds")


Time taken using Python lists: 119.652612 seconds


In [79]:
# Convert lists into NumPy arrays
array1 = np.array(matrix1)
array2 = np.array(matrix2)

start_time = time.time()
result_array = np.dot(array1, array2)
end_time = time.time()

print(f"Time taken using NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken using NumPy arrays: 1.367027 seconds
